version: '2.4'

services:
  valhalla_osm:
    image: gisops/valhalla:latest
    container_name: valhalla_osm
    ports:
      - "8000:8002"
    volumes:
      - ./data/osm/:/custom_files
    environment:
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
  valhalla_tomtom:
    image: gisops/valhalla:latest
    container_name: valhalla_tomtom
    ports:
      - "9000:8002"
    volumes:
      - ./data/tomtom/:/custom_files
    environment:
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
    depends_on:
      - valhalla_osm
  valhalla_here:
    image: gisops/valhalla:latest
    container_name: valhalla_here
    ports:
      - "9005:8002"
    volumes:
      - ./data/here/:/custom_files
    environment:
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
    depends_on:
      - valhalla_osm
  converter_demo:
    image: gisops/prop2osm-demo-app:latest
    container_name: prop2osm-demo-app
    ports:
      - "3005:80"
    environment:
      - VALHALLA_TOMTOM=http://localhost:9000
      - VALHALLA_OSM=http://localhost:8000
      - VALHALLA_HERE=http://localhost:9005
