version: '3.0'
services:
  valhalla_osm:
    image: gisops/valhalla:latest
    ports:
      - "8000:8002"
    volumes:
      - ./valhalla_osm/:/custom_files
    environment:
      # The tile_file must be located in the same folder as the volume mount.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=https://download.geofabrik.de/europe/austria-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=15 # -> Albania | -180 -> World
      - min_y=47 # -> Albania | -90  -> World
      - max_x=17 # -> Albania |  180 -> World
      - max_y=49 # -> Albania |  90  -> World
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
  valhalla_tomtom:
    image: gisops/valhalla:latest
    ports:
      - "9000:8002"
    volumes:
      - ./valhalla_tomtom/:/custom_files
    environment:
      # The tile_file must be located in the same folder as the volume mount.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=https://download.geofabrik.de/europe/austria-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=15 # -> Albania | -180 -> World
      - min_y=47 # -> Albania | -90  -> World
      - max_x=17 # -> Albania |  180 -> World
      - max_y=49 # -> Albania |  90  -> World
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
    depends_on:
      - valhalla_osm
  converter_demo:
    image: gisops/converter-demo-app:latest
    ports:
      - "3000:80"
    depends_on:
      - valhalla_osm
      - valhalla_tomtom
    environment:
      - VALHALLA_TOMTOM=http://localhost:9000
      - VALHALLA_OSM=http://localhost:8000
      - VALHALLA_HERE=http://localhost:9000
